version: '3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./phpmyadmin:/var/www/html
      - ./config/backend-nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    networks:
      - web-network

  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/htpasswd:/htpasswd
      - ./certs:/certs
      - ./phpmyadmin:/var/www/html
    links:
      - web
    networks:
      web-network:
        ipv4_address: 10.10.10.100



  php:
    image: my-php
    container_name: php
    build:
      context: .
    volumes:
      - ./phpmyadmin:/var/www/html
    links:
      - db
    networks:
      - web-network

  db:
    image: mysql/mysql-server:latest
    container_name: db
    environment:
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: phpmyadmin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - web-network


networks:
  web-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/24